services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db

  api:
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start:dev
    ports:
      - 3001:3001
    environment:
      - MONGODB_URI=mongodb://root:password@db:27017

volumes:
  db_data:
    